<a href="https://colab.research.google.com/github/Harshithgolla/AI-Amrita/blob/main/numpy/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NUMPY IN DIFFERENT WAYS***

In [1]:
import numpy as np

**lists**

In [2]:
PythonList = [41,29,48,35]
print(PythonList)


[41, 29, 48, 35]


**NUMPY**

In [3]:
numpy_array = np.array(PythonList)
numpy_array

array([41, 29, 48, 35])

In [4]:
a = numpy_array+12
print(a)

[53 41 60 47]


In [5]:
a = np.array([13,15,39])
print(a)

[13 15 39]


In [6]:
b = a +5
print(b)

[18 20 44]


In [7]:
print(a.shape)
print(a.dtype)

(3,)
int64


In [8]:
c = np.array([(12,32,38,43),
              (42,15,46,15)])
print(c)

[[12 32 38 43]
 [42 15 46 15]]


In [9]:
d = np.array([
    [[13,42,43],
        [43, 35, 26]],
      [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)

(2, 2, 3)


**TO PRINT 3 ROWS 3 COULMNS OF ZEROS**

In [10]:
x=np.ones((3,3), dtype=np.int16)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


**TO PRINT 3 TIMES OF 2 ROWS 4 COLUMNS OF zeros**

In [12]:
y=np.zeros((3,2,4), dtype=np.int16)
print(y)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]


**RESHAPE TO 1 ELEMENT LISTS**

In [14]:
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
print(e)

[[1 2 3]
 [4 5 6]]


In [16]:
print('First row:', e[0])
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [17]:
print('Second column:', e[:,1])

Second column: [2 5]


In [18]:
print(e[1, :2])

[4 5]


In [19]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

**HORITONTAL AND VERTICAL STACK**

In [21]:
f = np.array([13,12,33])
g = np.array([41,25,36])

print('Horizontal Append:', np.hstack((f, g)))
print("Vertical append:")
print(np.vstack((f,g)))

Horizontal Append: [13 12 33 41 25 36]
Vertical append:
[[13 12 33]
 [41 25 36]]


**TO FIND A LIST OF RANDOM ELEMENTS**

In [22]:
normal_array = np.random.normal(6, 10.5, 9)
print(normal_array)

[11.4608312   1.03667392  7.15738167 10.27386704 11.24449486 -1.76565344
 -0.34277867 26.76896452 33.03955531]


**FIND MIN , MAX, MEAN, MEDIAN,STD FROM A LISTS**

In [23]:
print(np.min(normal_array))
print(np.max(normal_array))
print(np.mean(normal_array))
print(np.median(normal_array))
print(np.std(normal_array))

-1.7656534431471904
33.03955530572182
10.985926268192255
10.273867041984357
11.258843376997412


**TO PRINT ELEMENTS IN RANGE**

In [26]:
np.arange(1, 8)

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
np.arange(1, 11,2)

array([1, 3, 5, 7, 9])

In [28]:
np.linspace(1.5, 10.5, num=22)

array([ 1.5       ,  1.92857143,  2.35714286,  2.78571429,  3.21428571,
        3.64285714,  4.07142857,  4.5       ,  4.92857143,  5.35714286,
        5.78571429,  6.21428571,  6.64285714,  7.07142857,  7.5       ,
        7.92857143,  8.35714286,  8.78571429,  9.21428571,  9.64285714,
       10.07142857, 10.5       ])

In [29]:
np.linspace(1.4, 6.0, num=6, endpoint=False)

array([1.4       , 2.16666667, 2.93333333, 3.7       , 4.46666667,
       5.23333333])

In [30]:
np.logspace(3.3, 4.0, num=4)

array([ 1995.26231497,  3414.54887383,  5843.41413374, 10000.        ])

In [31]:
x = np.array([21,32,34], dtype=np.complex128)
x.itemsize

16

**TO FIND DOT PRODUCT OF MATRIX**

In [32]:
f = np.array([21,42,53])
g = np.array([24,45,15])
np.dot(f, g)

3189

**TO FIND THE INVERSE OF MATRIX**

In [33]:
A = np.array([[16, 21, 31],
              [24, -2, 35],
              [22, 38, 27]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[-0.13765665  0.06077183  0.07927193]
 [ 0.01213447 -0.02486573  0.01830117]
 [ 0.09508653 -0.01452158 -0.05331211]]


**TO FIND THE MATRIX MULTIPLICATION**

In [34]:
h = [[13,22],[31,43]] 
i = [[51,64],[47,84]] 
np.matmul(h, i)

array([[1697, 2680],
       [3602, 5596]])

**TO FIND THE DETERMINANT OF MATRIX**

In [35]:
n_array = np.array([[45, 22], [56, 74]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[45 22]
 [56 74]]

Determinant of given 2X2 matrix:
2098


**TO FIND THE RANK OF MATRIX**

In [36]:
mx = np.array([[13,21,11],[10,13,24],[41,35,23]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

3

**TO FIND THE TRANSPOSE OF THE MATRIX**

In [38]:
gfg = np.matrix('[46, 21; 56, 43]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[46 56]
 [21 43]]


**TO FIND THE TRACE OF MATRIX**

In [39]:
gfg = np.matrix('[43, 21; 15, 43]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[86]]


**TO FIND THE EIGEN VALUES AND EIGEN VECTORS OF MATRIX**

In [40]:
example_matrix = np.array([
  [31,42,53,46],
  [53,64,57,38],
  [39,13,51,52],
  [33,44,16,45]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[168.02286915 +0.j         -11.97316255 +0.j
  17.4751467 +24.40084714j  17.4751467 -24.40084714j] [[-0.49687867+0.j          0.88352265+0.j         -0.14026129-0.00551996j
  -0.14026129+0.00551996j]
 [-0.63537398+0.j         -0.2734761 +0.j         -0.13161672+0.50293875j
  -0.13161672-0.50293875j]
 [-0.42069417+0.j         -0.3157669 +0.j         -0.37524257-0.46172199j
  -0.37524257+0.46172199j]
 [-0.4152444 +0.j         -0.21187219+0.j          0.59668398+0.j
   0.59668398-0.j        ]]
